// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClickItemContainer(arg1) {
  return window['go']['main']['App']['ClickItemContainer'](arg1);
}

export function ParseInput(arg1) {
  return window['go']['main']['App']['ParseInput'](arg1);
}
